# Generated by Django 5.1.5 on 2025-02-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='dni',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='DOCUMENTO DE IDENTIFICACIÓN'),
        ),
        migrations.AlterField(
            model_name='controlcosto',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='DESCRIPCIÓN DEL COSTO'),
        ),
        migrations.AlterField(
            model_name='controlcosto',
            name='fecha',
            field=models.DateField(verbose_name='FECHA DEL COSTO'),
        ),
        migrations.AlterField(
            model_name='controlcosto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VALOR DE LA COTIZACIÓN'),
        ),
        migrations.AlterField(
            model_name='controlcosto',
            name='reforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='web.reforma', verbose_name='FEROMAR DEL COSTO'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='COSTO ESTIMADO'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(verbose_name='DESCRIPCIÓN DE LA COTIZACIÓN'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='FECHA DE VENCIMIENTO'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proveedor',
            field=models.CharField(max_length=255, verbose_name='PROVEEDOR'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='reforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='web.reforma', verbose_name='REFORMA DE LA COTIZACIÓN'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPCIÓN'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='DIRECCIÓN'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50, verbose_name='ESTADO'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_adquisicion',
            field=models.DateField(verbose_name='FECHA DE ADQUISICIÓN'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='web.propietario', verbose_name='PROPIETARIO'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Oficina', 'Oficina')], max_length=100, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='CORREO:'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DIRECCIÓN'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='NOMBRE:'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TELÉFONO'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='COSTO ESTIMADO'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='costo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='COSTO REAL (DEJAR EN BLANCO SI AÚN NO SE TERMINA LA REFORMA)'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='descripcion',
            field=models.TextField(verbose_name='ACCIONES A REALIZAR'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada'), ('Pendiente', 'Pendiente')], max_length=50, verbose_name='ESTADO DE LA REFORMA'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='fecha_inicio',
            field=models.DateField(verbose_name='FECHA DE INICIO'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE FIN (DEJAR EN BLANCO SI NO SE HA FINALIZADO)'),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reformas', to='web.inmueble', verbose_name='INMUEBLE DE LA REFORMA'),
        ),
    ]
