# Generated by Django 5.1.5 on 2025-02-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_propietario_dni_alter_controlcosto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='foto',
            field=models.ImageField(null=True, upload_to='propietarios/', verbose_name='FOTO DEL PROPIETARIO:'),
        ),
    ]
