# Generated by Django 5.1.5 on 2025-02-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_propietario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcosto',
            name='foto',
            field=models.ImageField(null=True, upload_to='costos/', verbose_name='EVIDENCIA:'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='foto',
            field=models.ImageField(null=True, upload_to='inmuebles/', verbose_name='FOTO DEL INMUEBLE:'),
        ),
    ]
